package com.bancodebogota.wsldapppe.service.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-08-21T16:25:03.379-05:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "v1/WebServiceLdapPpe", 
                  wsdlLocation = "/wsdl/WebServiceLdapPpe_1.wsdl",
                  targetNamespace = "http://bancodebogota.com/WSLdapPPE/service/v1") 
public class V1_002fWebServiceLdapPpe_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bancodebogota.com/WSLdapPPE/service/v1", "v1/WebServiceLdapPpe");
    public final static QName WebServiceLdapPpeHttPort = new QName("http://bancodebogota.com/WSLdapPPE/service/v1", "WebServiceLdapPpeHttPort");
    static {
        URL url = V1_002fWebServiceLdapPpe_Service.class.getResource("/wsdl/WebServiceLdapPpe_1.wsdl");
        if (url == null) {
            url = V1_002fWebServiceLdapPpe_Service.class.getClassLoader().getResource("/wsdl/WebServiceLdapPpe_1.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(V1_002fWebServiceLdapPpe_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/wsdl/WebServiceLdapPpe_1.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public V1_002fWebServiceLdapPpe_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public V1_002fWebServiceLdapPpe_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public V1_002fWebServiceLdapPpe_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public V1_002fWebServiceLdapPpe_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public V1_002fWebServiceLdapPpe_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public V1_002fWebServiceLdapPpe_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns V1_002fWebServiceLdapPpe
     */
    @WebEndpoint(name = "WebServiceLdapPpeHttPort")
    public V1_002fWebServiceLdapPpe getWebServiceLdapPpeHttPort() {
        return super.getPort(WebServiceLdapPpeHttPort, V1_002fWebServiceLdapPpe.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns V1_002fWebServiceLdapPpe
     */
    @WebEndpoint(name = "WebServiceLdapPpeHttPort")
    public V1_002fWebServiceLdapPpe getWebServiceLdapPpeHttPort(WebServiceFeature... features) {
        return super.getPort(WebServiceLdapPpeHttPort, V1_002fWebServiceLdapPpe.class, features);
    }

}
